# ==========================================
# CONFIGURACION DEL MICROSERVICIO (PRODUCTO)
# ==========================================
server.port=8082

# Base de Datos H2 Local en Memoria
spring.datasource.url=jdbc:h2:mem:productodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuracion de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Firma Secreta requerida por el Filtro JWT (Evita la caída)
jwt.secret=MiClaveSecretaUltraSeguraParaElMicroservicioDeProductosDuocUC2026
jwt.expiration=86400000